Repository Team-Packman/Packman-Server-Release, pull requests merged in 2022-09, with the labels that each got.

#121 [FIX] cors 허용 url 수정
  src/index.ts
Labels: Bug🐞, 현지👻

#122 [CHORE] 최근 생성된 리스트 조회
  src/services/FolderService.ts
Labels: Enhancement⭐, 현지👻

#114 [FEAT] 혼자 패킹리스트 생성, 조회에 invite code 추가
  src/interfaces/IAloneList.ts
  src/modules/generateInviteCode.ts
  src/services/AloneListService.ts
  src/services/TogetherListService.ts
Labels: Enhancement⭐, GET🔮, POST📦, 서희🥑

#123 [FEAT] 공유된 혼자 패킹리스트 조회
  src/controllers/AloneListController.ts
  src/interfaces/IAloneList.ts
  src/modules/responseMessage.ts
  src/routes/AloneListRouter.ts
  src/services/AloneListService.ts
Labels: Enhancement⭐, GET🔮, 현지👻

#128 [CHORE] QA 이후 수정사항
  src/services/UserService.ts
Labels: Enhancement⭐, 서희🥑

#127 [CHORE] QA 수정사항
  src/controllers/ListController.ts
  src/interfaces/IList.ts
  src/middlewares/isLogin.ts
  src/routes/ListRouter.ts
  src/services/ListService.ts
  src/services/TogetherListService.ts
Labels: 경린🐣

#129 [FEAT] 공유된 패킹리스트 조회
  src/controllers/ListController.ts
  src/interfaces/IAloneList.ts
  src/interfaces/ITogetherList.ts
  src/modules/responseMessage.ts
  src/routes/ListRouter.ts
  src/routes/TogetherListRouter.ts
  src/services/ListService.ts
Labels: Enhancement⭐, GET🔮, 현지👻

#132 [FEAT] 초대 관련 API의 URI 통일
  src/controllers/ListController.ts
  src/controllers/TogetherListController.ts
  src/routes/ListRouter.ts
  src/routes/TogetherListRouter.ts
  src/services/ListService.ts
  src/services/TogetherListService.ts
Labels: Enhancement⭐, 현지👻

#130 [FEAT] 함께+혼자 패킹 inviteCode비교
  src/modules/generateInviteCode.ts
  src/services/AloneListService.ts
  src/services/TogetherListService.ts
Labels: 경린🐣

#141 [CHORE] 템플릿 안 카테고리 및 짐 정렬
  src/services/AloneListService.ts
  src/services/ListService.ts
  src/services/TogetherListService.ts
Labels: Enhancement⭐, 서희🥑

#143 [FIX] 폴더 조회에서 listNum 오류 수정
  src/modules/folderResponse.ts
Labels: Bug🐞, 경린🐣

#138 [CHORE] 혼자 패킹리스트 삭제 시 folder와의 연결 끊기
  src/services/AloneListService.ts
Labels: Enhancement⭐, 서희🥑

#146 [FEAT] 함께 패킹 그룹 멤버 조회 responseBody에 inviteCode 추가
  src/interfaces/IMember.ts
  src/services/MemberService.ts
Labels: Enhancement⭐, 현지👻

#150 [CHORE]/#149 함께 패킹 멤버 여러명 삭제 가능하도록 수정
  src/services/MemberService.ts
Labels: Enhancement⭐, 현지👻

#140 [FEAT] 유저 권한 설정
  src/controllers/AloneListPackController.ts
  src/controllers/TogetherListPackController.ts
  src/modules/aloneListCategoryCheckResponse.ts
  src/modules/togetherListCategoryCheckResponse.ts
  src/services/AloneListPackService.ts
  src/services/TogetherListPackService.ts
Labels: Enhancement⭐, 현지👻

#139 [FEAT] 유저 권한 설정
  src/controllers/AloneListController.ts
  src/controllers/ListController.ts
  src/controllers/TogetherListController.ts
  src/interfaces/IAloneList.ts
  src/interfaces/ITogetherList.ts
  src/modules/aloneListCheckResponse.ts
  src/modules/folderCheckResponse.ts
  src/modules/togetherListCheckResponse.ts
  src/services/AloneListService.ts
  src/services/ListService.ts
  src/services/TogetherListService.ts
Labels: Enhancement⭐, 서희🥑

#158 [CHORE] 패킹리스트 상세조회 response body에 folderId 추가
  src/interfaces/IAloneList.ts
  src/interfaces/ITogetherList.ts
  src/modules/togetherListCheckResponse.ts
  src/services/AloneListService.ts
  src/services/TogetherListService.ts
Labels: Enhancement⭐, 서희🥑

#159 [FEAT] transaction 적용 & service단 console.log 제거
  src/services/AloneListService.ts
  src/services/AuthService.ts
  src/services/ListService.ts
  src/services/TemplateService.ts
  src/services/TogetherListService.ts
  src/services/UserService.ts
Labels: Enhancement⭐, 서희🥑

#157 [FEAT] tansaction적용
  src/services/AloneListCategoryService.ts
  src/services/FolderService.ts
  src/services/TogetherListCategoryService.ts
  src/services/TogetherListService.ts
  src/services/UserService.ts
Labels: Enhancement⭐, 경린🐣

#156 [FEAT] transaction 적용
  src/services/AloneListPackService.ts
  src/services/MemberService.ts
  src/services/TogetherListPackService.ts
  src/services/UserService.ts
Labels: Enhancement⭐, 현지👻

#160 [CHORE] transaction관련 수정 사항 및 service의 필요없는 try-catch문 제거
  src/controllers/FolderController.ts
  src/controllers/MemberController.ts
  src/controllers/TemplateController.ts
  src/controllers/TogetherListController.ts
  src/services/AloneListCategoryService.ts
  src/services/AloneListPackService.ts
  src/services/AloneListService.ts
  src/services/AuthService.ts
  src/services/FolderService.ts
  src/services/LandingService.ts
  src/services/ListService.ts
  src/services/MemberService.ts
  src/services/TemplateService.ts
  src/services/TogetherListCategoryService.ts
  src/services/TogetherListPackService.ts
  src/services/TogetherListService.ts
  src/services/UserService.ts
Labels: 현지👻

#165 [FIX] 혼자 패킹리스트 짐 관련 module 오류 해결
  src/modules/aloneListCategoryCheckResponse.ts
Labels: Bug🐞, 현지👻

#167 [CHORE] 닉네임, 프로필 등록 API의 requestBody에 path 추가
  src/interfaces/IAuth.ts
  src/interfaces/IUser.ts
  src/routes/UserRouter.ts
  src/services/UserService.ts
Labels: Enhancement⭐, 현지👻

#169 [FEAT] 엿보기 조회 틀 구현
  src/controllers/HelpController.ts
  src/modules/responseMessage.ts
  src/routes/HelpRouter.ts
  src/routes/index.ts
  src/services/HelpService.ts
Labels: Enhancement⭐, 현지👻
