Repository Team-Packman/Packman-Server-Release, pull requests merged in 2022-08, with the labels that each got.

#29 [FEAT] 함께 패킹리스트 초대
  src/controllers/ListController.ts
  src/controllers/index.ts
  src/interfaces/IPackingListDto.ts
  src/routes/ListRouter.ts
  src/routes/index.ts
  src/services/ListService.ts
  src/services/index.ts
Labels: Enhancement⭐, GET🔮, 경린🐣

#12 [FEAT] 함께 패킹리스트 짐 생성
  src/controllers/TogetherListPackController.ts
  src/controllers/UserController.ts
  src/controllers/index.ts
  src/interfaces/IPack.ts
  src/modules/responseMessage.ts
  src/routes/TogetherListPackRouter.ts
  src/routes/UserRouter.ts
  src/routes/index.ts
  src/services/TogetherListPackService.ts
  src/services/index.ts
Labels: Enhancement⭐, POST📦, 현지👻

#13 [FEAT] 함께 패킹리스트 짐 수정
  src/controllers/TogetherListPackController.ts
  src/interfaces/IPack.ts
  src/modules/responseMessage.ts
  src/routes/TogetherListPackRouter.ts
  src/services/TogetherListPackService.ts
Labels: Enhancement⭐, PATCH✂, 현지👻

#14 [FEAT] 함께 패킹리스트 짐 삭제
  src/controllers/TogetherListPackController.ts
  src/controllers/TogetherPackingListPackController.ts
  src/interfaces/IPack.ts
  src/routes/TogetherListPackRouter.ts
  src/services/TogetherListPackService.ts
  src/services/UserService.ts
Labels: Enhancement⭐, DELETE💥, 현지👻

#24 [FEAT] 최근 생성된 리스트 조회
  package.json
  src/controllers/FolderController.ts
  src/interfaces/IList.ts
  src/modules/responseMessage.ts
  src/routes/FolderRouter.ts
  src/routes/index.ts
  src/services/FolderService.ts
  yarn.lock
Labels: Enhancement⭐, GET🔮, 현지👻

#16 [FEAT] 카카오 로그인, 회원가입
  package.json
  src/controllers/AuthController.ts
  src/controllers/UserController.ts
  src/controllers/index.ts
  src/interfaces/IUser.ts
  src/interfaces/common/JwtPayloadInfo.ts
  src/middlewares/Auth.ts
  src/modules/jwtHandler.ts
  src/modules/responseMessage.ts
  src/routes/AuthRouter.ts
  src/routes/index.ts
  src/services/AuthService.ts
  src/services/UserService.ts
  src/services/index.ts
  yarn.lock
Labels: Enhancement⭐, POST📦, 서희🥑

#17 [FEAT] 닉네임, 프로필 등록
  package.json
  src/controllers/UserController.ts
  src/interfaces/IUser.ts
  src/routes/UserRouter.ts
  src/services/UserService.ts
  yarn.lock
Labels: Enhancement⭐, POST📦, 서희🥑

#22 [FEAT] 함께 패킹리스트 생성
  src/controllers/TogetherListController.ts
  src/interfaces/ITogetherList.ts
  src/modules/responseMessage.ts
  src/routes/TogetherListRouter.ts
  src/services/TogetherListService.ts
  src/services/index.ts
Labels: Enhancement⭐, POST📦, 서희🥑

#25 [FEAT] 함께 패킹리스트 상세조회
  src/controllers/TogetherListController.ts
  src/interfaces/ITogetherList.ts
  src/routes/TogetherListRouter.ts
  src/services/TogetherListService.ts
Labels: Enhancement⭐, GET🔮, 서희🥑

#28 [FEAT] 함께 패킹리스트 담당자 배정 구현
  src/controllers/TogetherListController.ts
  src/interfaces/ITogetherList.ts
  src/modules/responseMessage.ts
  src/routes/TogetherListRouter.ts
  src/services/TogetherListService.ts
Labels: Enhancement⭐, PATCH✂, 서희🥑

#32 [CHORE] 1주차 API 관련 MERGE 후 수정 사항
  src/services/TogetherListService.ts
  src/services/UserService.ts
Labels: 서희🥑

#41 [CHORE] 모듈 import 구조 통일 및 최근 생성된 리스트 Service 수정
  src/routes/TogetherListCategoryRouter.ts
  src/routes/TogetherListPackRouter.ts
  src/services/FolderService.ts
Labels: Enhancement⭐, 현지👻

#30 [FEAT] 토큰 재발급
  src/config/index.ts
  src/controllers/AuthController.ts
  src/interfaces/IAuth.ts
  src/interfaces/IUser.ts
  src/middlewares/auth.ts
  src/modules/jwtHandler.ts
  src/modules/responseMessage.ts
  src/routes/AuthRouter.ts
  src/routes/UserRouter.ts
  src/services/AuthService.ts
  src/services/UserService.ts
Labels: Enhancement⭐, GET🔮, 현지👻

#36 [CHORE] 함께, 혼자 패킹리스트 카테고리 조회 모듈화
  src/interfaces/IAloneList.ts
  src/interfaces/ICategory.ts
  src/interfaces/IList.ts
  src/interfaces/IPack.ts
  src/interfaces/IPackingListDto.ts
  src/interfaces/ITogetherList.ts
  src/interfaces/ITogetherListCategory.ts
  src/modules/aloneCategoryResponse.ts
  src/modules/togetherCategoryResponse.ts
  src/services/ListService.ts
  src/services/TogetherListCategoryService.ts
  src/services/TogetherListPackService.ts
  src/services/TogetherListService.ts
Labels: Enhancement⭐, 서희🥑, 현지👻

#44 [FEAT] 랜딩 페이지 사용자 등록
  src/controllers/LandingController.ts
  src/controllers/index.ts
  src/interfaces/ILanding.ts
  src/modules/responseMessage.ts
  src/routes/LandingRouter.ts
  src/routes/index.ts
  src/services/LandingService.ts
  src/services/index.ts
Labels: Enhancement⭐, POST📦, 현지👻

#45 [FEAT] 1주차 API 배포 전 수정사항
  package-lock.json
  package.json
  src/config/index.ts
  src/controllers/AuthController.ts
  src/controllers/FolderController.ts
  src/controllers/ListController.ts
  src/controllers/TogetherListCategoryController.ts
  src/controllers/TogetherListController.ts
  src/controllers/TogetherListPackController.ts
  src/controllers/UserController.ts
  src/index.ts
  src/interfaces/IList.ts
  src/loaders/db.ts
  src/middlewares/auth.ts
  src/modules/responseMessage.ts
  src/routes/FolderRouter.ts
  src/routes/ListRouter.ts
  src/routes/TogetherListCategoryRouter.ts
  src/routes/TogetherListPackRouter.ts
  src/routes/TogetherListRouter.ts
  src/services/AuthService.ts
  src/services/FolderService.ts
  src/services/ListService.ts
  src/services/TogetherListService.ts
  yarn.lock
Labels: Enhancement⭐, 현지👻

#74 [CHORE] 랜딩 페이지 사용자 등록
  src/index.ts
  src/modules/responseMessage.ts
Labels: Enhancement⭐, 현지👻

#64 [FEAT] 패킹리스트 제목 수정
  src/controllers/ListController.ts
  src/interfaces/IList.ts
  src/routes/ListRouter.ts
  src/services/ListService.ts
Labels: Enhancement⭐, PATCH✂, 서희🥑

#66 [FEAT] 패킹리스트 출발 날짜 수정
  src/controllers/ListController.ts
  src/interfaces/IList.ts
  src/routes/ListRouter.ts
  src/services/ListService.ts
Labels: Enhancement⭐, PATCH✂, 서희🥑

#46 [FEAT] 폴더 생성
  src/controllers/FolderController.ts
  src/interfaces/IFolder.ts
  src/modules/folderResponse.ts
  src/routes/FolderRouter.ts
  src/services/FolderService.ts
Labels: Enhancement⭐, POST📦, 경린🐣

#49 [FEAT] 혼자 패킹리스트 카테고리 생성
  src/controllers/AloneListCategoryController.ts
  src/controllers/index.ts
  src/routes/AloneListCategoryRouter.ts
  src/routes/index.ts
  src/services/AloneListCategoryService.ts
  src/services/index.ts
Labels: Enhancement⭐, POST📦, 경린🐣

#51 [FEAT] 혼자 패킹 리스트 카테고리 수정
  src/controllers/AloneListCategoryController.ts
  src/routes/AloneListCategoryRouter.ts
  src/services/AloneListCategoryService.ts
Labels: Enhancement⭐, PATCH✂, 경린🐣

#55 [FEAT] 혼자 패킹 리스트 카테고리 삭제
  src/controllers/AloneListCategoryController.ts
  src/routes/AloneListCategoryRouter.ts
  src/services/AloneListCategoryService.ts
Labels: Enhancement⭐, DELETE💥, 경린🐣

#73 [FEAT] 폴더 조회
  src/controllers/FolderController.ts
  src/routes/FolderRouter.ts
  src/services/FolderService.ts
Labels: Enhancement⭐, GET🔮, 경린🐣

#60 [FEAT] 혼자 패킹리스트 생성
  src/controllers/AloneListController.ts
  src/controllers/TogetherListController.ts
  src/controllers/index.ts
  src/interfaces/IAloneList.ts
  src/interfaces/IList.ts
  src/interfaces/ITogetherList.ts
  src/routes/AloneListRouter.ts
  src/routes/index.ts
  src/services/AloneListService.ts
  src/services/TogetherListService.ts
  src/services/index.ts
Labels: Enhancement⭐, POST📦, 서희🥑

#62 [FEAT] 혼자 패킹리스트 조회
  src/controllers/AloneListController.ts
  src/routes/AloneListRouter.ts
  src/services/AloneListService.ts
Labels: Enhancement⭐, GET🔮, 서희🥑

#70 [FEAT] 패킹리스트 나만의 템플릿 추가 및 업데이트
  src/controllers/ListController.ts
  src/interfaces/IList.ts
  src/routes/ListRouter.ts
  src/services/ListService.ts
Labels: Enhancement⭐, PATCH✂, 서희🥑

#78 [CHORE] 1주차 API 수정
  src/services/TogetherListService.ts
Labels: 서희🥑

#37 [FEAT] 함께 패킹리스트 폴더 조회
  src/controllers/FolderController.ts
  src/interfaces/IFolder.ts
  src/modules/responseMessage.ts
  src/routes/FolderRouter.ts
  src/services/FolderService.ts
  src/services/index.ts
Labels: Enhancement⭐, GET🔮, 현지👻

#38 [FEAT] 혼자 패킹리스트 폴더 조회
  src/controllers/FolderController.ts
  src/modules/responseMessage.ts
  src/routes/FolderRouter.ts
  src/services/FolderService.ts
Labels: Enhancement⭐, GET🔮, 현지👻

#53 [FEAT] 폴더 안 함께 패킹 리스트 조회
  src/controllers/FolderController.ts
  src/interfaces/IFolder.ts
  src/modules/responseMessage.ts
  src/routes/FolderRouter.ts
  src/services/FolderService.ts
Labels: Enhancement⭐, GET🔮, 현지👻

#56 [FEAT] 폴더 안 혼자 패킹리스트 조회
  src/controllers/FolderController.ts
  src/controllers/IFolder.ts
  src/modules/responseMessage.ts
  src/routes/FolderRouter.ts
  src/services/FolderService.ts
Labels: Enhancement⭐, GET🔮, 현지👻

#68 [FEAT] 혼자 패킹리스트 짐 생성
  src/controllers/AloneListPackController.ts
  src/controllers/index.ts
  src/modules/responseMessage.ts
  src/routes/AloneListPackRouter.ts
  src/routes/index.ts
  src/services/AloneListPackService.ts
  src/services/index.ts
Labels: Enhancement⭐, POST📦, 현지👻

#69 [FEAT] 혼자 패킹리스트 짐 수정
  src/controllers/AloneListPackController.ts
  src/interfaces/IPack.ts
  src/routes/AloneListPackRouter.ts
  src/services/AloneListPackService.ts
Labels: Enhancement⭐, PATCH✂, 현지👻

#71 [FEAT] 혼자 패킹리스트 짐 삭제
  src/controllers/AloneListPackController.ts
  src/routes/AloneListPackRouter.ts
  src/services/AloneListPackService.ts
Labels: Enhancement⭐, DELETE💥, 현지👻

#76 [FEAT] 1주차 api 수정사항
  src/services/TogetherListCategoryService.ts
Labels: 경린🐣

#87 [CHORE] 1주차, 2주차 API 수정사항
  src/controllers/AloneListCategoryController.ts
  src/controllers/AloneListController.ts
  src/controllers/AloneListPackController.ts
  src/controllers/FolderController.ts
  src/controllers/IFolder.ts
  src/controllers/LandingController.ts
  src/controllers/ListController.ts
  src/controllers/TogetherListCategoryController.ts
  src/controllers/TogetherListController.ts
  src/controllers/TogetherListPackController.ts
  src/controllers/UserController.ts
  src/interfaces/IFolder.ts
  src/modules/responseMessage.ts
  src/routes/AloneListCategoryRouter.ts
  src/routes/AloneListPackRouter.ts
  src/routes/LandingRouter.ts
  src/routes/UserRouter.ts
  src/services/AloneListCategoryService.ts
  src/services/AloneListPackService.ts
  src/services/AloneListService.ts
  src/services/AuthService.ts
  src/services/FolderService.ts
  src/services/LandingService.ts
  src/services/ListService.ts
  src/services/TogetherListCategoryService.ts
  src/services/TogetherListPackService.ts
  src/services/TogetherListService.ts
  src/services/UserService.ts
Labels: Enhancement⭐, 현지👻

#82 [FEAT] 혼자 패킹 템플릿 리스트 조회
  src/config/index.ts
  src/controllers/TemplateController.ts
  src/controllers/index.ts
  src/interfaces/ITemplate.ts
  src/modules/templateListResponse.ts
  src/routes/TemplateRouter.ts
  src/routes/index.ts
  src/services/TemplateService.ts
  src/services/index.ts
Labels: Enhancement⭐, GET🔮, 서희🥑

#83 [FEAT] 함께 패킹 템플릿 리스트 조회
  src/controllers/IFolder.ts
  src/controllers/TemplateController.ts
  src/routes/TemplateRouter.ts
  src/services/TemplateService.ts
  src/services/index.ts
Labels: Enhancement⭐, GET🔮, 서희🥑

#85 [FEAT] 폴더 수정
  src/controllers/FolderController.ts
  src/interfaces/IFolder.ts
  src/modules/folderResponse.ts
  src/routes/FolderRouter.ts
  src/services/FolderService.ts
Labels: Enhancement⭐, PATCH✂, 경린🐣

#92 [FEAT] 회원 조회하기
  src/controllers/UserController.ts
  src/routes/UserRouter.ts
  src/services/UserService.ts
Labels: Enhancement⭐, GET🔮, 현지👻

#97 [FEAT] 회원 정보 수정
  src/controllers/IFolder.ts
  src/controllers/UserController.ts
  src/interfaces/IUser.ts
  src/routes/UserRouter.ts
  src/services/UserService.ts
Labels: Enhancement⭐, PATCH✂, 경린🐣

#94 [FEAT] 템플릿 상세 조회
  src/controllers/TemplateController.ts
  src/interfaces/ITemplate.ts
  src/modules/responseMessage.ts
  src/routes/TemplateRouter.ts
  src/services/TemplateService.ts
  src/services/index.ts
Labels: Enhancement⭐, GET🔮, 경린🐣

#105 [CHORE] 함께, 혼자 패킹리스트 templateId 빈 문자열 처리 수정
  src/routes/AloneListRouter.ts
  src/routes/TogetherListRouter.ts
  src/services/AloneListService.ts
  src/services/TogetherListService.ts
Labels: Enhancement⭐, 서희🥑

#106 [CHORE] userId 타입 수정 및 들여쓰기 수정
  src/modules/templateListResponse.ts
  src/services/TemplateService.ts
Labels: Enhancement⭐, 서희🥑

#103 [FEAT] 폴더 속 함께 패킹리스트 삭제
  src/config/index.ts
  src/controllers/TogetherListController.ts
  src/interfaces/IList.ts
  src/interfaces/ITogetherList.ts
  src/modules/responseMessage.ts
  src/routes/TogetherListRouter.ts
  src/services/TogetherListService.ts
Labels: Enhancement⭐, 서희🥑, DELETE💥

#101 [FEAT] 함께 패킹 그룹 멤버 조회
  src/controllers/MemberController.ts
  src/controllers/index.ts
  src/interfaces/IMember.ts
  src/modules/responseMessage.ts
  src/routes/MemberRouter.ts
  src/routes/index.ts
  src/services/MemberService.ts
  src/services/index.ts
Labels: Enhancement⭐, GET🔮, 현지👻

#98 [FEAT] 폴더 속 혼자 패킹리스트 삭제
  src/controllers/AloneListController.ts
  src/interfaces/IAloneList.ts
  src/interfaces/IFolder.ts
  src/modules/responseMessage.ts
  src/routes/AloneListRouter.ts
  src/services/AloneListService.ts
Labels: Enhancement⭐, 서희🥑, DELETE💥

#89 [FEAT] 폴더 삭제
  src/controllers/FolderController.ts
  src/modules/responseMessage.ts
  src/routes/FolderRouter.ts
  src/services/FolderService.ts
Labels: Enhancement⭐, DELETE💥, 경린🐣

#96 [FEAT] 회원 탈퇴하기
  src/controllers/UserController.ts
  src/modules/responseMessage.ts
  src/routes/UserRouter.ts
  src/services/AuthService.ts
  src/services/UserService.ts
Labels: Enhancement⭐, DELETE💥, 현지👻

#110 [CHORE] 함께 패킹 그룹 멤버 조회, 폴더 안 함께 패킹리스트 조회 수정
  src/controllers/MemberController.ts
  src/modules/responseMessage.ts
  src/routes/MemberRouter.ts
  src/services/FolderService.ts
  src/services/MemberService.ts
Labels: Enhancement⭐, 현지👻

#108 [FEAT] 함께 패킹 그룹 멤버 삭제
  src/controllers/MemberController.ts
  src/interfaces/IMember.ts
  src/modules/responseMessage.ts
  src/routes/MemberRouter.ts
  src/services/MemberService.ts
Labels: Enhancement⭐, DELETE💥, 현지👻

#113 [FEAT] 함께 패킹 초대에 isMember 추가
  src/controllers/ListController.ts
  src/interfaces/IList.ts
  src/middlewares/isLogin.ts
  src/routes/ListRouter.ts
  src/services/ListService.ts
Labels: GET🔮, 경린🐣

#118 [CHORE] 그룹원 추가 수정
  src/services/TogetherListService.ts
Labels: Enhancement⭐, 현지👻
